#!/usr/bin/env python3
"""Daily AI-bot traffic parser for api.pepperoni.tatar.

Reads /var/log/nginx/ai-bots.log (or yesterday's rotated *.gz),
produces a Markdown digest with:

  * Total hits, unique paths, unique IPs per bot
  * Top 20 most-fetched paths overall
  * Per-bot top 5 paths
  * Status-code distribution (200 / 304 / 404 / 5xx)
  * Bytes served per bot
  * Diff vs the previous day (was the digest run yesterday)

Writes the digest to:
  /var/log/nginx/ai-bots-digest-YYYY-MM-DD.md
  /var/log/nginx/ai-bots-digest-latest.md       (symlink)

Then prints the digest path to stdout — suitable for a cron job that
pipes the output to a Telegram bot or email.

Usage:
  python3 parse-ai-bots.py              # parses yesterday's rotated log
  python3 parse-ai-bots.py --today      # parses the live log (debug)
  python3 parse-ai-bots.py --file PATH  # explicit path

Cron entry (add to /etc/cron.d/pepperoni-ai-bots):
  5 6 * * *  root  /usr/bin/python3 /opt/pepperoni-api/infra/scripts/parse-ai-bots.py | xargs -I{} cat {} | mail -s "AI bots digest" admin@kazandelikates.tatar
"""
from __future__ import annotations
import argparse
import datetime as dt
import gzip
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

LOG_DIR = Path(os.environ.get("AI_BOTS_LOG_DIR", "/var/log/nginx"))
DIGEST_DIR = Path(os.environ.get("AI_BOTS_DIGEST_DIR", "/var/log/nginx"))


def open_log(path: Path):
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def parse_lines(path: Path):
    """Yield parsed JSON dicts from a log file."""
    if not path.exists():
        return
    with open_log(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                # legacy / corrupted line — skip
                continue


def aggregate(records):
    by_bot = defaultdict(lambda: {
        "hits": 0,
        "ips": set(),
        "paths": Counter(),
        "status": Counter(),
        "bytes": 0,
    })
    overall_paths = Counter()
    overall_status = Counter()
    for r in records:
        bot = r.get("bot") or "unknown"
        b = by_bot[bot]
        b["hits"] += 1
        b["ips"].add(r.get("ip", "?"))
        path = r.get("path", "?")
        b["paths"][path] += 1
        s = r.get("status", 0)
        b["status"][s] += 1
        b["bytes"] += int(r.get("bytes") or 0)
        overall_paths[path] += 1
        overall_status[s] += 1
    return by_bot, overall_paths, overall_status


def fmt_bytes(n):
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024.0:
            return f"{n:.1f} {unit}"
        n /= 1024.0
    return f"{n:.1f} TB"


def build_digest(date_label, by_bot, overall_paths, overall_status, total):
    lines = []
    lines.append(f"# AI-bot traffic — {date_label}")
    lines.append("")
    lines.append(f"- **Total bot hits**: {total}")
    lines.append(f"- **Unique paths hit**: {len(overall_paths)}")
    lines.append(f"- **Unique bots**: {len(by_bot)}")
    lines.append("")
    lines.append("## Hits by bot")
    lines.append("")
    lines.append("| Bot | Hits | Unique IPs | Bytes | 2xx | 3xx | 4xx | 5xx |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    for bot, b in sorted(by_bot.items(), key=lambda kv: -kv[1]["hits"]):
        s = b["status"]
        twoxx = sum(v for k, v in s.items() if 200 <= k < 300)
        threexx = sum(v for k, v in s.items() if 300 <= k < 400)
        fourxx = sum(v for k, v in s.items() if 400 <= k < 500)
        fivexx = sum(v for k, v in s.items() if 500 <= k < 600)
        lines.append(
            f"| `{bot}` | {b['hits']} | {len(b['ips'])} | {fmt_bytes(b['bytes'])} | "
            f"{twoxx} | {threexx} | {fourxx} | {fivexx} |"
        )
    lines.append("")
    lines.append("## Top 20 paths (all bots combined)")
    lines.append("")
    lines.append("| # | Path | Hits |")
    lines.append("|---:|---|---:|")
    for i, (p, c) in enumerate(overall_paths.most_common(20), 1):
        lines.append(f"| {i} | `{p}` | {c} |")
    lines.append("")
    for bot, b in sorted(by_bot.items(), key=lambda kv: -kv[1]["hits"]):
        if b["hits"] < 5:
            continue
        lines.append(f"### Top 5 paths for `{bot}`")
        lines.append("")
        for i, (p, c) in enumerate(b["paths"].most_common(5), 1):
            lines.append(f"  {i}. `{p}` — {c}")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Generated by `infra/scripts/parse-ai-bots.py`.")
    lines.append("Source log: `/var/log/nginx/ai-bots.log[.N.gz]`.")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--today", action="store_true",
                    help="parse the live log instead of yesterday's")
    ap.add_argument("--file", type=str, help="explicit path to log file")
    args = ap.parse_args()

    if args.file:
        log_path = Path(args.file)
        label = log_path.name
    elif args.today:
        log_path = LOG_DIR / "ai-bots.log"
        label = "today"
    else:
        # yesterday's rotated log: ai-bots.log.1 or .1.gz
        for cand in ("ai-bots.log.1", "ai-bots.log.1.gz"):
            p = LOG_DIR / cand
            if p.exists():
                log_path = p
                break
        else:
            print(
                f"ERROR: no rotated yesterday log in {LOG_DIR}. "
                "Use --today or --file to override.",
                file=sys.stderr,
            )
            return 2
        label = (dt.date.today() - dt.timedelta(days=1)).isoformat()

    records = list(parse_lines(log_path))
    by_bot, overall_paths, overall_status = aggregate(records)
    digest = build_digest(label, by_bot, overall_paths, overall_status, len(records))

    DIGEST_DIR.mkdir(parents=True, exist_ok=True)
    today = dt.date.today().isoformat()
    out = DIGEST_DIR / f"ai-bots-digest-{today}.md"
    out.write_text(digest, encoding="utf-8")
    latest = DIGEST_DIR / "ai-bots-digest-latest.md"
    try:
        if latest.exists() or latest.is_symlink():
            latest.unlink()
        latest.symlink_to(out.name)
    except OSError:
        latest.write_text(digest, encoding="utf-8")

    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
