#!/usr/bin/env python3
"""Apply EN geo cleanup from data/en_geo_cleanup_analysis.json.

Deletes 410 HTML under public/en/geo/, leaves keep/hold, writes nginx
exact 301s (if any) + prefix /en/geo/ → 410 when missing, rebuilds sitemap.
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
ANALYSIS = ROOT / "data" / "en_geo_cleanup_analysis.json"
NGINX_DIR = ROOT / "deploy" / "nginx"


def main() -> int:
    d = json.loads(ANALYSIS.read_text(encoding="utf-8"))
    if d.get("gate", {}).get("verdict") != "ok":
        print("refuse: gate not ok", d.get("gate"), file=sys.stderr)
        return 2
    rows = d["dispositions"]
    counts = Counter(r["disposition"] for r in rows)
    print("dispositions:", dict(counts))

    deleted = Counter()
    for r in rows:
        if r["disposition"] not in ("410", "301"):
            continue
        f = PUBLIC / r["file"]
        if f.exists():
            f.unlink()
            deleted[r["disposition"]] += 1
    print("deleted:", dict(deleted))

    # 301 nginx (may be empty)
    lines = [
        "# AUTO-GENERATED by scripts/apply_en_geo_cleanup.py",
        "# EN geo residual impressions → /en/… parents. Include before gone.conf.",
        "",
    ]
    n301 = 0
    for r in sorted(rows, key=lambda x: x["stem"]):
        if r["disposition"] != "301" or not r.get("parent"):
            continue
        stem, parent = r["stem"], r["parent"]
        target = f"https://pepperoni.tatar{parent}"
        lines.append(f"location = /en/geo/{stem} {{ return 301 {target}; }}")
        lines.append(f"location = /en/geo/{stem}.html {{ return 301 {target}; }}")
        n301 += 1
    NGINX_DIR.mkdir(parents=True, exist_ok=True)
    (NGINX_DIR / "en-geo-cleanup-redirects.conf").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    print(f"301 nginx stems: {n301}")

    (NGINX_DIR / "en-geo-cleanup-gone.conf").write_text(
        """# AUTO-GENERATED by scripts/apply_en_geo_cleanup.py
# Surviving keep/hold EN geo served; deleted → 410 (not @vercel).
location ^~ /en/geo/ {
    try_files $uri $uri.html =410;
}
""",
        encoding="utf-8",
    )

    en_my = PUBLIC / "en" / "myasnyie-zagotovki.html"
    if en_my.exists():
        en_my.unlink()
        print("deleted en/myasnyie-zagotovki.html")

    subprocess.check_call([sys.executable, str(ROOT / "scripts" / "rebuild_sitemap.py")])
    remaining = list((PUBLIC / "en" / "geo").glob("*.html"))
    expected = counts["keep"] + counts["hold"]
    print(f"remaining en/geo: {len(remaining)} (expected {expected})")
    if len(remaining) != expected:
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
