#!/usr/bin/env python3
"""
Apply approved blog near-dup clusters from data/blog_dedup_audit.json:

1. Rename duplicate HTML → public/blog/_removed_{slug}.bak (and EN mirrors)
2. Rewrite internal hrefs pointing at duplicates → canonical
3. Emit nginx snippet deploy/nginx/pepperoni-blog-redirects.conf
4. Merge 301s into vercel.json redirects
5. Rebuild blog index + sitemap

Usage:
  python3 scripts/apply_blog_canonicals.py           # apply approved
  python3 scripts/apply_blog_canonicals.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
AUDIT = ROOT / "data" / "blog_dedup_audit.json"
VERCEL = ROOT / "vercel.json"
NGINX_OUT = ROOT / "deploy" / "nginx" / "pepperoni-blog-redirects.conf"


def load_clusters(lang: str) -> list[dict]:
    data = json.loads(AUDIT.read_text(encoding="utf-8"))
    key = "clusters_ru" if lang == "ru" else "clusters_en"
    return [c for c in data.get(key, []) if c.get("approved", True) and c.get("redirect_from")]


def rename_dupes(clusters: list[dict], lang: str, dry: bool) -> list[tuple[str, str]]:
    """Return list of (from_path, to_path) redirects applied."""
    redirects = []
    base = PUBLIC / "blog" if lang == "ru" else PUBLIC / "en" / "blog"
    prefix = "/blog" if lang == "ru" else "/en/blog"
    for c in clusters:
        canon = c["canonical"]
        canon_file = base / f"{canon}.html"
        if not canon_file.exists():
            print(f"  ⚠️  missing canon {canon_file}, skip cluster")
            continue
        for slug in c["redirect_from"]:
            src = base / f"{slug}.html"
            if not src.exists():
                # already removed?
                bak = base / f"_removed_{slug}.bak"
                if bak.exists():
                    redirects.append((f"{prefix}/{slug}", f"{prefix}/{canon}"))
                continue
            bak = base / f"_removed_{slug}.bak"
            print(f"  rename {src.relative_to(ROOT)} → {bak.name}")
            if not dry:
                if bak.exists():
                    bak.unlink()
                src.rename(bak)
            redirects.append((f"{prefix}/{slug}", f"{prefix}/{canon}"))
            # EN mirror of the same slug (if present)
            if lang == "ru":
                en_src = PUBLIC / "en" / "blog" / f"{slug}.html"
                if en_src.exists():
                    en_bak = PUBLIC / "en" / "blog" / f"_removed_{slug}.bak"
                    print(f"  rename {en_src.relative_to(ROOT)} → {en_bak.name}")
                    if not dry:
                        if en_bak.exists():
                            en_bak.unlink()
                        en_src.rename(en_bak)
                    en_dst = (
                        f"/en/blog/{canon}"
                        if (PUBLIC / "en" / "blog" / f"{canon}.html").exists()
                        else f"/blog/{canon}"
                    )
                    redirects.append((f"/en/blog/{slug}", en_dst))
    return redirects


def rewrite_internal_links(redirects: list[tuple[str, str]], dry: bool) -> int:
    """Replace href="/blog/dup" → href="/blog/canon" across public/**/*.html."""
    if not redirects:
        return 0
    # longest sources first
    pairs = sorted(redirects, key=lambda x: -len(x[0]))
    changed_files = 0
    for html in PUBLIC.rglob("*.html"):
        if html.name.startswith("_removed_"):
            continue
        text = html.read_text(encoding="utf-8", errors="replace")
        orig = text
        for src, dst in pairs:
            # href="/blog/foo" or href='/blog/foo' or with trailing slash
            for quote in ('"', "'"):
                text = text.replace(f"href={quote}{src}{quote}", f"href={quote}{dst}{quote}")
                text = text.replace(f"href={quote}{src}/{quote}", f"href={quote}{dst}{quote}")
                text = text.replace(
                    f"https://pepperoni.tatar{src}",
                    f"https://pepperoni.tatar{dst}",
                )
        if text != orig:
            changed_files += 1
            print(f"  linkfix {html.relative_to(ROOT)}")
            if not dry:
                html.write_text(text, encoding="utf-8")
    return changed_files


def write_nginx(redirects: list[tuple[str, str]], dry: bool) -> None:
    NGINX_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/apply_blog_canonicals.py — do not edit by hand.",
        "# Install on VPS: cp to /etc/nginx/snippets/ && include from pepperoni.tatar;",
        "",
    ]
    for src, dst in sorted(set(redirects)):
        # exact location match
        lines.append(f"location = {src} {{ return 301 https://pepperoni.tatar{dst}; }}")
    text = "\n".join(lines) + "\n"
    print(f"  nginx snippet → {NGINX_OUT.relative_to(ROOT)} ({len(redirects)} rules)")
    if not dry:
        NGINX_OUT.write_text(text, encoding="utf-8")


def merge_vercel(redirects: list[tuple[str, str]], dry: bool) -> None:
    data = json.loads(VERCEL.read_text(encoding="utf-8"))
    existing = data.setdefault("redirects", [])
    have = {(r.get("source"), r.get("destination")) for r in existing}
    added = 0
    for src, dst in sorted(set(redirects)):
        key = (src, dst)
        if key in have:
            continue
        # also skip if source already redirected elsewhere
        if any(r.get("source") == src for r in existing):
            continue
        existing.append({
            "source": src,
            "destination": dst,
            "permanent": True,
        })
        have.add(key)
        added += 1
    print(f"  vercel.json +{added} redirects (total {len(existing)})")
    if not dry:
        VERCEL.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def rebuild(dry: bool) -> None:
    if dry:
        print("  (dry-run) skip rebuild_blog_index / rebuild_sitemap")
        return
    for script in ("rebuild_blog_index.py", "rebuild_sitemap.py"):
        path = ROOT / "scripts" / script
        if not path.exists():
            print(f"  ⚠️  missing {script}")
            continue
        print(f"  run {script}")
        subprocess.run([sys.executable, str(path)], cwd=ROOT, check=False)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    if not AUDIT.exists():
        print(f"❌ missing {AUDIT} — run scripts/audit_blog_duplicates.py first")
        return 1

    dry = args.dry_run
    print(f"{'DRY-RUN ' if dry else ''}Applying blog canonicals from {AUDIT.name}")

    all_redirects: list[tuple[str, str]] = []
    for lang in ("ru", "en"):
        clusters = load_clusters(lang)
        print(f"\n== {lang.upper()}: {len(clusters)} approved clusters ==")
        all_redirects.extend(rename_dupes(clusters, lang, dry))

    # dedupe redirects
    uniq = sorted(set(all_redirects))
    print(f"\n== {len(uniq)} redirect rules ==")
    n = rewrite_internal_links(uniq, dry)
    print(f"  files with link fixes: {n}")
    write_nginx(uniq, dry)
    merge_vercel(uniq, dry)
    rebuild(dry)
    print("\n✅ done" + (" (dry-run)" if dry else ""))
    print("   VPS: copy deploy/nginx/pepperoni-blog-redirects.conf → "
          "/etc/nginx/snippets/ and include it, then nginx -t && reload")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
