#!/usr/bin/env python3
"""Apply geo-cleanup dispositions from data/geo_cleanup_analysis.json.

Owner go 2026-07-23: whitelist=clicks-only, 410+301 one commit,
delete /myasnyie-zagotovki category, commit analytics + fix_links.

Actions:
  1. Delete public/geo/*.html with disposition=410
  2. Generate deploy/nginx/geo-cleanup-redirects.conf (301)
  3. Generate deploy/nginx/geo-cleanup-gone.conf (/geo/ missing → 410)
  4. Strip 410 geo anchors from pepperoni.html / en/pepperoni.html
     (301 links left as /geo/… — nginx returns 301)
  5. Delete public/myasnyie-zagotovki.html
  6. Rebuild sitemap

Nginx install on VPS is a separate step after push (snippets + include).
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
ANALYSIS = ROOT / "data" / "geo_cleanup_analysis.json"
NGINX_DIR = ROOT / "deploy" / "nginx"


def load_rows() -> list[dict]:
    d = json.loads(ANALYSIS.read_text(encoding="utf-8"))
    if d.get("gate", {}).get("verdict") != "ok":
        raise SystemExit(f"refuse: gate not ok: {d.get('gate')}")
    return d["dispositions"]


def delete_removed(rows: list[dict]) -> dict:
    """Delete HTML for 410 (gone) and 301 (redirect handled by nginx).

    keep/hold files stay on disk. 301 files must NOT stay — otherwise they
    remain in rebuild_sitemap scans and dilute the cleanup signal.
    """
    counts = Counter()
    for r in rows:
        if r["disposition"] not in ("410", "301"):
            continue
        f = PUBLIC / r["file"]
        if f.exists():
            f.unlink()
            counts[r["disposition"]] += 1
    return dict(counts)


def write_301_nginx(rows: list[dict]) -> int:
    lines = [
        "# AUTO-GENERATED by scripts/apply_geo_cleanup.py — do not edit by hand.",
        "# 301 geo pages with residual GSC impressions → live category parent.",
        "# Include inside HTTPS server {} for pepperoni.tatar BEFORE geo-cleanup-gone.conf.",
        "",
    ]
    n = 0
    for r in sorted(rows, key=lambda x: x["stem"]):
        if r["disposition"] != "301" or not r.get("parent"):
            continue
        stem, parent = r["stem"], r["parent"]
        target = f"https://pepperoni.tatar{parent}"
        lines.append(f"location = /geo/{stem} {{ return 301 {target}; }}")
        lines.append(f"location = /geo/{stem}.html {{ return 301 {target}; }}")
        n += 1
    NGINX_DIR.mkdir(parents=True, exist_ok=True)
    (NGINX_DIR / "geo-cleanup-redirects.conf").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    return n


def write_gone_nginx() -> None:
    text = """# AUTO-GENERATED by scripts/apply_geo_cleanup.py — do not edit by hand.
# Surviving keep/hold geo HTML files are served; deleted geo return 410 Gone
# (must NOT fall through to @vercel). Include AFTER geo-cleanup-redirects.conf.
location ^~ /geo/ {
    try_files $uri $uri.html =410;
}

# Category page for discontinued product line (owner 2026-07-22/23).
location = /myasnyie-zagotovki { return 410; }
location = /myasnyie-zagotovki.html { return 410; }
"""
    (NGINX_DIR / "geo-cleanup-gone.conf").write_text(text, encoding="utf-8")


def clean_inbound(rows: list[dict]) -> dict:
    gone = {r["stem"] for r in rows if r["disposition"] == "410"}
    stats = Counter()
    # Remove entire <a href="/geo/STEM"...>...</a> for 410 stems
    anchor_re = re.compile(
        r'<a\s+href="/(?:en/)?geo/([a-z0-9\-]+)(?:\.html)?/?"[^>]*>.*?</a>\s*',
        re.DOTALL | re.IGNORECASE,
    )

    def drop_or_keep(m: re.Match) -> str:
        stem = m.group(1)
        if stem in gone:
            stats["dropped_410_anchors"] += 1
            return ""
        stats["kept_anchors"] += 1
        return m.group(0)

    touched = {}
    for rel in ("pepperoni.html", "en/pepperoni.html"):
        f = PUBLIC / rel
        if not f.exists():
            continue
        html = f.read_text(encoding="utf-8")
        new = anchor_re.sub(drop_or_keep, html)
        if new != html:
            f.write_text(new, encoding="utf-8")
            touched[rel] = True
    return {"files": list(touched), "stats": dict(stats)}


def main() -> int:
    rows = load_rows()
    counts = Counter(r["disposition"] for r in rows)
    print("dispositions:", dict(counts))

    deleted = delete_removed(rows)
    print(f"deleted files: {deleted}")

    n301 = write_301_nginx(rows)
    print(f"wrote 301 nginx locations for {n301} stems")
    write_gone_nginx()
    print("wrote geo-cleanup-gone.conf")

    my = (PUBLIC / "myasnyie-zagotovki.html")
    if my.exists():
        my.unlink()
        print("deleted myasnyie-zagotovki.html")
    else:
        print("myasnyie-zagotovki.html already absent")

    inbound = clean_inbound(rows)
    print("inbound cleanup:", inbound)

    subprocess.check_call([sys.executable, str(ROOT / "scripts" / "rebuild_sitemap.py")])

    remaining = list((PUBLIC / "geo").glob("*.html"))
    expected = counts["keep"] + counts["hold"]
    print(f"remaining public/geo/*.html: {len(remaining)} (expected {expected})")
    sm = (PUBLIC / "sitemap.xml").read_text(encoding="utf-8")
    print(f"sitemap /geo/ mentions: {sm.count('/geo/')}")
    if len(remaining) != expected:
        print("ERROR: remaining geo count != keep+hold", file=sys.stderr)
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
