#!/usr/bin/env python3
"""Reconcile the SKU count everywhere it is hardcoded as text.

Single source of truth: public/products.json -> totalProducts (written by
sync-sheets.mjs from the live Google Sheets catalog). This script patches the
static files that mention the SKU count in prose but are NOT regenerated by
any pipeline step so they never drift from the live catalog again.

Run this after every sync-sheets.mjs run (wired into sync-vps.sh) — it is
idempotent and a no-op if the count already matches.

Usage: python3 scripts/reconcile_sku_count.py [--check]
  --check   exit 1 if any target file is out of sync, without writing (CI use)
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent.parent
PUBLIC = ROOT / "public"
PRODUCTS_JSON = PUBLIC / "products.json"
STATE_FILE = ROOT / "data" / "sku_count_state.json"


def ru_tovar(n: int) -> str:
    n10, n100 = n % 10, n % 100
    if n10 == 1 and n100 != 11:
        return f"{n} товар"
    if 2 <= n10 <= 4 and not (12 <= n100 <= 14):
        return f"{n} товара"
    return f"{n} товаров"


def ru_naimenovanie(n: int) -> str:
    n10, n100 = n % 10, n % 100
    if n10 == 1 and n100 != 11:
        return f"{n} наименование"
    if 2 <= n10 <= 4 and not (12 <= n100 <= 14):
        return f"{n} наименования"
    return f"{n} наименований"


SECTION_LABELS_EN = {
    "Заморозка": "frozen meats",
    "Охлаждённая продукция": "refrigerated/chilled meats",
    "Выпечка": "bakery",
}


def get_live_data() -> dict:
    data = json.loads(PRODUCTS_JSON.read_text(encoding="utf-8"))
    products = data.get("products", [])
    n = data.get("totalProducts")
    if not isinstance(n, int) or n <= 0:
        n = len(products)
    if not n:
        raise SystemExit("reconcile_sku_count: could not determine live SKU count")

    counts = Counter(p.get("section") for p in products)
    frozen = counts.get("Заморозка", 0)
    chilled = counts.get("Охлаждённая продукция", 0)
    bakery = counts.get("Выпечка", 0)

    parts = []
    for ru_name, en_label in SECTION_LABELS_EN.items():
        c = counts.get(ru_name)
        if c:
            parts.append(f"{en_label} ({c} SKUs)")
    if len(parts) > 1:
        sections_en = ", ".join(parts[:-1]) + f", and {parts[-1]}"
    else:
        sections_en = parts[0] if parts else ""

    return {
        "n": n,
        "ru": ru_tovar(n),
        "ru_name": ru_naimenovanie(n),
        "sections_en": sections_en,
        "frozen": frozen,
        "chilled": chilled,
        "bakery": bakery,
        "n8": n * 8,
    }


def render(template: str, ctx: dict) -> str:
    return template.format(**ctx)


# (file, [(regex, replacement_template)]) — templates use {n}/{ru}/{ru_name}/…
TARGETS: list[tuple[Path, list[tuple[str, str]]]] = [
    (
        PUBLIC / "manifest.json",
        [
            (r"\d+ товаров\. Актуальные цены", "{ru}. Актуальные цены"),
        ],
    ),
    (
        PUBLIC / ".well-known" / "ai-plugin.json",
        [
            (r"Казанских Деликатесов: \d+ товаров —", "Казанских Деликатесов: {ru} —"),
            (r"catalog contains \d+ SKUs across", "catalog contains {n} SKUs across"),
            (
                r"frozen meats \(\d+ SKUs\), refrigerated/chilled meats \(\d+ SKUs\), and bakery \(\d+ SKUs\)",
                "{sections_en}",
            ),
            (r"full company profile, \d+ detailed product cards", "full company profile, {n} detailed product cards"),
        ],
    ),
    (
        PUBLIC / ".well-known" / "mcp.json",
        [
            (r"Казанские Деликатесы\)\. \d+ SKUs,", "Казанские Деликатесы). {n} SKUs,"),
        ],
    ),
    (
        PUBLIC / "ai.json",
        [
            (r'"numberOfItems":\s*\d+', '"numberOfItems": {n}'),
        ],
    ),
    (
        PUBLIC / ".well-known" / "ai-meta.json",
        [
            (r'"product_count":\s*\d+', '"product_count": {n}'),
            (r"all \d+ SKU detail cards", "all {n} SKU detail cards"),
            (r"\d+ halal meat products", "{n} halal meat products"),
            (r"XML sitemap covering \d+ RU \+ \d+ EN product pages",
             "XML sitemap covering {n} RU + {n} EN product pages"),
            (r"\(TSV, \d+ SKUs\)", "(TSV, {n} SKUs)"),
            (r"\d+ halal SKUs with full attribute set", "{n} halal SKUs with full attribute set"),
            (r"\d+ halal SKUs\. Registered", "{n} halal SKUs. Registered"),
            (r"\d+ items \(\d+ SKUs × 8 countries\)", "{n8} items ({n} SKUs × 8 countries)"),
        ],
    ),
    (
        PUBLIC / "openapi.yaml",
        [
            (r"\d+ products across 3 sections", "{n} products across 3 sections"),
        ],
    ),
    (
        PUBLIC / "about.html",
        [
            (r"\d+ наименования\. Сертификат Halal", "{ru_name}. Сертификат Halal"),
            (r'"numberOfItems":\s*\d+,(\s*"itemListElement")',
             '"numberOfItems": {n},\\1'),
            (r'("name": "Заморозка", "numberOfItems": )\d+', r"\g<1>{frozen}"),
            (r'("name": "Охлаждённая продукция", "numberOfItems": )\d+', r"\g<1>{chilled}"),
            (r'("name": "Выпечка", "numberOfItems": )\d+', r"\g<1>{bakery}"),
            (r'(<span class="num">)\d+(</span><span class="label">наименований продукции</span>)',
             r"\g<1>{n}\2"),
            (r"всего \d+ SKUs,", "всего {n} SKUs,"),
            (r"<strong>\d+ наименовани[яй]</strong>", "<strong>{ru_name}</strong>"),
            (r"JSON, \d+ товара?, синхронизация", "JSON, {ru}, синхронизация"),
        ],
    ),
    (
        PUBLIC / "en" / "about.html",
        [
            (r'"numberOfItems":\s*\d+,(\s*"itemListElement")',
             '"numberOfItems": {n},\\1'),
            (r'("name": "Frozen Products", "numberOfItems": )\d+', r"\g<1>{frozen}"),
            (r'("name": "Refrigerated Products", "numberOfItems": )\d+', r"\g<1>{chilled}"),
            (r'("name": "Bakery", "numberOfItems": )\d+', r"\g<1>{bakery}"),
            (r"\d+ SKUs · 7 currencies", "{n} SKUs · 7 currencies"),
            (r"\d+ SKUs total,", "{n} SKUs total,"),
            (r"\d+ halal SKUs · HACCP", "{n} halal SKUs · HACCP"),
            (r"(<span class=\"num\">)\d+(</span>)", r"\g<1>{n}\2"),
        ],
    ),
    (
        PUBLIC / "faq-ai.txt",
        [
            (r"\d+ SKU\. Без свинины", "{n} SKU. Без свинины"),
            (r"(A4: )\d+( SKU\.)", r"\g<1>{n}\2"),
        ],
    ),
    (
        PUBLIC / "llm.txt",
        [
            (r"> \d+ SKU halal catalog\.", "> {n} SKU halal catalog."),
            (r"## Live product catalog \(\d+ SKUs,", "## Live product catalog ({n} SKUs,"),
        ],
    ),
    (
        PUBLIC / "rss.xml",
        [
            # Only the channel description line — not product prices containing 72/77.
            (r"(<description>Каталог халяль продукции: )\d+ товаров( —)",
             r"\g<1>{ru}\2"),
        ],
    ),
    (
        PUBLIC / "faq.html",
        [
            # Prepositional: «о всех N товарах» (not genitive «товаров»).
            (r"о всех \d+ товарах в формате JSON", "о всех {n} товарах в формате JSON"),
            (r"производит \d+ наименовани[яй]", "производит {ru_name}"),
        ],
    ),
    (
        PUBLIC / "en" / "faq.html",
        [
            (r"produces \d+ product items:", "produces {n} product items:"),
            (r"on all \d+ products in JSON format", "on all {n} products in JSON format"),
        ],
    ),
    (
        PUBLIC / ".well-known" / "llms.txt",
        [
            (r"# \d+ halal meat products and Tatar pastries\.",
             "# {n} halal meat products and Tatar pastries."),
            (r"- \d+ products: pepperoni,", "- {n} products: pepperoni,"),
            (r"Sections: Frozen \(\d+\), Refrigerated \(\d+\), Bakery \(\d+\)",
             "Sections: Frozen ({frozen}), Refrigerated ({chilled}), Bakery ({bakery})"),
        ],
    ),
]


def patch_file(path: Path, rules: list[tuple[str, str]], ctx: dict, check_only: bool) -> tuple[bool, bool]:
    """Returns (would_change_or_changed, wrote)."""
    if not path.exists():
        print(f"  [skip] {path.relative_to(ROOT)} does not exist")
        return False, False
    text = path.read_text(encoding="utf-8")
    original = text
    for pattern, template in rules:
        repl = render(template, ctx)

        def _sub(m: re.Match, _repl=repl) -> str:
            out = _repl
            out = out.replace("\\1", m.group(1) if m.lastindex and m.lastindex >= 1 else "")
            out = out.replace("\\2", m.group(2) if m.lastindex and m.lastindex >= 2 else "")
            for i in range(1, (m.lastindex or 0) + 1):
                out = out.replace(f"\\g<{i}>", m.group(i))
            return out

        if "\\1" in repl or "\\g<" in repl or "\\2" in repl:
            text = re.sub(pattern, _sub, text)
        else:
            text = re.sub(pattern, repl, text)
    # Fix about section headings (any digit → live section count)
    if path.name == "about.html" and path.parent == PUBLIC:
        text = re.sub(
            r"❄️ Заморозка \(\d+ товар(?:а|ов)?\)",
            f"❄️ Заморозка ({ru_tovar(ctx['frozen'])})",
            text,
        )
        text = re.sub(
            r"🧊 Охлаждённая продукция \(\d+ товар(?:а|ов)?\)",
            f"🧊 Охлаждённая продукция ({ru_tovar(ctx['chilled'])})",
            text,
        )
        text = re.sub(
            r"🥐 Выпечка \(\d+ товар(?:а|ов)?\)",
            f"🥐 Выпечка ({ru_tovar(ctx['bakery'])})",
            text,
        )
    if text == original:
        print(f"  [ok] {path.relative_to(ROOT)} already matches ({ctx['n']})")
        return False, False
    if check_only:
        print(f"  [MISMATCH] {path.relative_to(ROOT)}")
        return True, False
    path.write_text(text, encoding="utf-8")
    print(f"  [fixed] {path.relative_to(ROOT)}")
    return True, True


def save_state(n: int) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    prev = None
    if STATE_FILE.exists():
        try:
            prev = json.loads(STATE_FILE.read_text(encoding="utf-8")).get("current")
        except Exception:
            prev = None
    STATE_FILE.write_text(
        json.dumps({"previous": prev, "current": n}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    check_only = "--check" in sys.argv
    ctx = get_live_data()
    print(f"Live SKU count (products.json.totalProducts): {ctx['n']}")
    print(
        f"  sections: frozen={ctx['frozen']} chilled={ctx['chilled']} bakery={ctx['bakery']}"
    )

    any_mismatch = False
    any_changed = False
    for path, rules in TARGETS:
        if not path.exists():
            continue
        mismatched, wrote = patch_file(path, rules, ctx, check_only)
        any_mismatch = any_mismatch or mismatched
        any_changed = any_changed or wrote

    if not check_only:
        save_state(ctx["n"])

    if check_only:
        if any_mismatch:
            print("reconcile_sku_count --check: mismatches found")
            return 1
        print("reconcile_sku_count --check: all files in sync")
        return 0

    if any_changed:
        print("reconcile_sku_count: patched drifted file(s)")
    else:
        print("reconcile_sku_count: nothing to do, all in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
