#!/usr/bin/env python3
"""Reconcile the SKU count everywhere it is hardcoded as text.

Single source of truth: public/products.json -> totalProducts (written by
sync-sheets.mjs from the live Google Sheets catalog). This script patches the
static files that mention the SKU count in prose but are NOT regenerated by
any pipeline step (manifest.json, ai-plugin.json, mcp.json, ai.json) so they
never drift from the live catalog again.

Run this after every sync-sheets.mjs run (wired into sync-vps.sh) — it is
idempotent and a no-op if the count already matches.

Usage: python3 scripts/reconcile_sku_count.py [--check]
  --check   exit 1 if any target file is out of sync, without writing (CI use)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PUBLIC = ROOT / "public"
PRODUCTS_JSON = PUBLIC / "products.json"

# Russian "товар" declension for a bare count (1, 2-4, 5+ with the usual
# 11-14 exception) — good enough for the counts this catalog will ever have.
def ru_tovar(n: int) -> str:
    n10, n100 = n % 10, n % 100
    if n10 == 1 and n100 != 11:
        return f"{n} товар"
    if 2 <= n10 <= 4 and not (12 <= n100 <= 14):
        return f"{n} товара"
    return f"{n} товаров"


# (file, [(regex, replacement_template)]) — replacement_template uses {n}/{ru}
# Patterns are deliberately narrow (fixed surrounding words) so they only
# touch the whole-catalog count, never per-section breakdowns.
TARGETS: list[tuple[Path, list[tuple[str, str]]]] = [
    (
        PUBLIC / "manifest.json",
        [
            (r"\d+ товаров\. Актуальные цены", "{ru}. Актуальные цены"),
        ],
    ),
    (
        PUBLIC / ".well-known" / "ai-plugin.json",
        [
            (r"Казанских Деликатесов: \d+ товаров —", "Казанских Деликатесов: {ru} —"),
            (r"catalog contains \d+ SKUs across", "catalog contains {n} SKUs across"),
            (
                r"frozen meats \(\d+ SKUs\), refrigerated/chilled meats \(\d+ SKUs\), and bakery \(\d+ SKUs\)",
                "{sections}",
            ),
            (r"full company profile, \d+ detailed product cards", "full company profile, {n} detailed product cards"),
        ],
    ),
    (
        PUBLIC / ".well-known" / "mcp.json",
        [
            (r"Казанские Деликатесы\)\. \d+ SKUs,", "Казанские Деликатесы). {n} SKUs,"),
        ],
    ),
    (
        PUBLIC / "ai.json",
        [
            (r'"numberOfItems":\s*\d+', '"numberOfItems": {n}'),
        ],
    ),
]


SECTION_LABELS = {
    "Заморозка": "frozen meats",
    "Охлаждённая продукция": "refrigerated/chilled meats",
    "Выпечка": "bakery",
}


def get_live_data() -> tuple[int, str]:
    data = json.loads(PRODUCTS_JSON.read_text(encoding="utf-8"))
    products = data.get("products", [])
    n = data.get("totalProducts")
    if not isinstance(n, int) or n <= 0:
        n = len(products)
    if not n:
        raise SystemExit("reconcile_sku_count: could not determine live SKU count")

    from collections import Counter

    counts = Counter(p.get("section") for p in products)
    parts = []
    for ru_name, en_label in SECTION_LABELS.items():
        c = counts.get(ru_name)
        if c:
            parts.append(f"{en_label} ({c} SKUs)")
    sections_str = ", ".join(parts[:-1]) + f", and {parts[-1]}" if len(parts) > 1 else (parts[0] if parts else "")
    return n, sections_str


def render(template: str, n: int, sections: str) -> str:
    return template.format(n=n, ru=ru_tovar(n), sections=sections)


def patch_file(path: Path, rules: list[tuple[str, str]], n: int, sections: str) -> bool:
    if not path.exists():
        print(f"  [skip] {path} does not exist")
        return False
    text = path.read_text(encoding="utf-8")
    original = text
    for pattern, template in rules:
        text = re.sub(pattern, render(template, n, sections), text)
    if text != original:
        path.write_text(text, encoding="utf-8")
        print(f"  [fixed] {path.relative_to(ROOT)}")
        return True
    print(f"  [ok] {path.relative_to(ROOT)} already matches ({n})")
    return False


def main() -> int:
    check_only = "--check" in sys.argv
    n, sections = get_live_data()
    print(f"Live SKU count (products.json.totalProducts): {n}")

    any_changed = False
    any_mismatch = False
    for path, rules in TARGETS:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        would_change = False
        for pattern, template in rules:
            if re.sub(pattern, render(template, n, sections), text) != text:
                would_change = True
                break
        if would_change:
            any_mismatch = True
            if check_only:
                print(f"  [MISMATCH] {path.relative_to(ROOT)}")
                continue
        changed = False if check_only else patch_file(path, rules, n, sections)
        any_changed = any_changed or changed

    if check_only:
        if any_mismatch:
            print("reconcile_sku_count --check: mismatches found")
            return 1
        print("reconcile_sku_count --check: all files in sync")
        return 0

    if any_changed:
        print("reconcile_sku_count: patched drifted file(s)")
    else:
        print("reconcile_sku_count: nothing to do, all in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
